import { NextRequest, NextResponse } from 'next/server';
import { handleApiError } from '@/lib/utils/errors';
import { getShopFromRequest } from '@/lib/shopify/get-shop';
import {
  getAuditReportData,
  getVisibilityReportData,
  generateAuditCsv,
  generateVisibilityCsv,
  generateAuditReportJson,
  generateSummaryReport,
} from '@/lib/services/reporting';
import { logger } from '@/lib/monitoring/logger';

// GET - Get report data
export async function GET(request: NextRequest) {
  try {
    const shopDomain = await getShopFromRequest(request, { rateLimit: false });
    const { searchParams } = new URL(request.url);

    const type = searchParams.get('type') || 'audit'; // audit | visibility
    const format = searchParams.get('format') || 'json'; // json | csv | txt

    logger.info({ shopDomain, type, format }, 'Report requested');

    let data;
    let content: string;
    let contentType: string;
    let filename: string;

    if (type === 'visibility') {
      data = await getVisibilityReportData(shopDomain);
      filename = `surfaced-aeo-visibility-report-${new Date().toISOString().split('T')[0]}`;

      if (format === 'csv') {
        content = generateVisibilityCsv(data);
        contentType = 'text/csv';
        filename += '.csv';
      } else if (format === 'txt') {
        // Generate text summary for visibility
        const visibilityLines = [
          '='.repeat(60),
          'SURFACED AEO VISIBILITY REPORT',
          `Store: ${data.shop.name} (${data.shop.domain})`,
          `Generated: ${new Date(data.generatedAt).toLocaleString()}`,
          '='.repeat(60),
          '',
          'SUMMARY',
          '-'.repeat(40),
          `Total Checks: ${data.summary.totalChecks}`,
          `Times Mentioned: ${data.summary.mentionedCount}`,
          `Mention Rate: ${data.summary.mentionRate}%`,
          `Average Position: ${data.summary.averagePosition || 'N/A'}`,
          '',
          'CHECKS DETAIL',
          '-'.repeat(40),
          ...data.checks.slice(0, 50).map(c =>
            `${c.platform}: "${c.query}" - ${c.isMentioned ? `Mentioned #${c.position || '?'}` : 'Not mentioned'}`
          ),
          '',
          '='.repeat(60),
          'Report generated by Surfaced - https://surfaced.vercel.app',
          '='.repeat(60),
        ];
        content = visibilityLines.join('\n');
        contentType = 'text/plain';
        filename += '.txt';
      } else {
        content = JSON.stringify(data, null, 2);
        contentType = 'application/json';
        filename += '.json';
      }
    } else if (type === 'summary') {
      // Summary report - always returns text
      data = await getAuditReportData(shopDomain);
      filename = `surfaced-aeo-summary-report-${new Date().toISOString().split('T')[0]}`;
      content = generateSummaryReport(data);
      contentType = 'text/plain';
      filename += '.txt';
    } else {
      // Default: audit report
      data = await getAuditReportData(shopDomain);
      filename = `surfaced-aeo-audit-report-${new Date().toISOString().split('T')[0]}`;

      if (format === 'csv') {
        content = generateAuditCsv(data);
        contentType = 'text/csv';
        filename += '.csv';
      } else if (format === 'txt') {
        content = generateSummaryReport(data);
        contentType = 'text/plain';
        filename += '.txt';
      } else {
        content = generateAuditReportJson(data);
        contentType = 'application/json';
        filename += '.json';
      }
    }

    // If download is requested, return as file
    if (searchParams.get('download') === 'true') {
      return new NextResponse(content, {
        headers: {
          'Content-Type': contentType,
          'Content-Disposition': `attachment; filename="${filename}"`,
        },
      });
    }

    // Otherwise return as JSON response
    return NextResponse.json({
      success: true,
      data: {
        content,
        contentType,
        filename,
        reportData: data,
      },
    });
  } catch (error) {
    logger.error({ error }, 'Report generation failed');
    return handleApiError(error);
  }
}
