import { describe, it, expect } from 'vitest';
import {
  generateLlmsTxt,
  type GenerateLlmsTxtOptions,
  type LlmsTxtProduct,
  type LlmsTxtCollection,
  type LlmsTxtStore,
} from '@/lib/services/llms-txt';
import type { LlmsTxtConfig } from '@prisma/client';

// Mock data
const mockStore: LlmsTxtStore = {
  name: 'Test Store',
  domain: 'test-store.myshopify.com',
  description: 'A great test store for testing.',
};

const mockConfig: LlmsTxtConfig = {
  id: 'config-1',
  shopId: 'shop-1',
  isEnabled: true,
  allowedBots: ['ChatGPT-User', 'GPTBot', 'ClaudeBot'],
  includeProducts: true,
  includeCollections: true,
  includeBlog: false,
  excludedProductIds: [],
  customInstructions: null,
  lastGeneratedAt: null,
  createdAt: new Date(),
  updatedAt: new Date(),
};

const mockProducts: LlmsTxtProduct[] = [
  {
    id: 'prod-1',
    title: 'Awesome T-Shirt',
    handle: 'awesome-t-shirt',
    description: '<p>A really <strong>awesome</strong> t-shirt made from 100% cotton.</p>',
    productType: 'Apparel',
    vendor: 'Test Brand',
    priceRange: {
      minVariantPrice: { amount: '29.99', currencyCode: 'USD' },
      maxVariantPrice: { amount: '29.99', currencyCode: 'USD' },
    },
    availableForSale: true,
  },
  {
    id: 'prod-2',
    title: 'Cool Sneakers',
    handle: 'cool-sneakers',
    description: 'Premium sneakers for everyday wear.',
    productType: 'Footwear',
    vendor: 'Test Brand',
    priceRange: {
      minVariantPrice: { amount: '99.00', currencyCode: 'USD' },
      maxVariantPrice: { amount: '149.00', currencyCode: 'USD' },
    },
    availableForSale: true,
  },
  {
    id: 'prod-3',
    title: 'Sold Out Item',
    handle: 'sold-out-item',
    description: 'This item is no longer available.',
    productType: 'Apparel',
    vendor: 'Test Brand',
    priceRange: null,
    availableForSale: false,
  },
];

const mockCollections: LlmsTxtCollection[] = [
  {
    id: 'col-1',
    title: 'Summer Collection',
    handle: 'summer-collection',
    description: 'Our best summer products.',
  },
  {
    id: 'col-2',
    title: 'New Arrivals',
    handle: 'new-arrivals',
    description: null,
  },
];

describe('llms-txt service', () => {
  describe('generateLlmsTxt', () => {
    it('should generate valid llms.txt with all sections', () => {
      const options: GenerateLlmsTxtOptions = {
        store: mockStore,
        config: mockConfig,
        products: mockProducts,
        collections: mockCollections,
      };

      const result = generateLlmsTxt(options);

      // Check H1 title (required)
      expect(result).toContain('# Test Store');

      // Check blockquote summary
      expect(result).toContain('> Test Store is an e-commerce store');

      // Check store description
      expect(result).toContain('A great test store for testing.');

      // Check AI crawlers section
      expect(result).toContain('## AI Crawlers');
      expect(result).toContain('ChatGPT-User');
      expect(result).toContain('GPTBot');
      expect(result).toContain('ClaudeBot');

      // Check products section
      expect(result).toContain('## Products');
      expect(result).toContain('[Awesome T-Shirt]');
      expect(result).toContain('[Cool Sneakers]');
      expect(result).toContain('USD 29.99');
      expect(result).toContain('USD 99.00 - 149.00');

      // Check collections section
      expect(result).toContain('## Collections');
      expect(result).toContain('[Summer Collection]');
      expect(result).toContain('[New Arrivals]');

      // Check optional section
      expect(result).toContain('## Optional');

      // Check footer
      expect(result).toContain('Generated by');
      expect(result).toContain('Surfaced');
    });

    it('should strip HTML from descriptions', () => {
      const options: GenerateLlmsTxtOptions = {
        store: mockStore,
        config: mockConfig,
        products: mockProducts,
        collections: mockCollections,
      };

      const result = generateLlmsTxt(options);

      // HTML should be stripped
      expect(result).not.toContain('<p>');
      expect(result).not.toContain('</p>');
      expect(result).not.toContain('<strong>');
      expect(result).toContain('A really awesome t-shirt');
    });

    it('should exclude unavailable products', () => {
      const options: GenerateLlmsTxtOptions = {
        store: mockStore,
        config: mockConfig,
        products: mockProducts,
        collections: mockCollections,
      };

      const result = generateLlmsTxt(options);

      // Sold out item should not be included
      expect(result).not.toContain('Sold Out Item');
    });

    it('should exclude specified product IDs', () => {
      const configWithExclusions: LlmsTxtConfig = {
        ...mockConfig,
        excludedProductIds: ['prod-1'],
      };

      const options: GenerateLlmsTxtOptions = {
        store: mockStore,
        config: configWithExclusions,
        products: mockProducts,
        collections: mockCollections,
      };

      const result = generateLlmsTxt(options);

      // Excluded product should not appear
      expect(result).not.toContain('Awesome T-Shirt');
      expect(result).toContain('Cool Sneakers');
    });

    it('should skip products section when disabled', () => {
      const configNoProducts: LlmsTxtConfig = {
        ...mockConfig,
        includeProducts: false,
      };

      const options: GenerateLlmsTxtOptions = {
        store: mockStore,
        config: configNoProducts,
        products: mockProducts,
        collections: mockCollections,
      };

      const result = generateLlmsTxt(options);

      expect(result).not.toContain('## Products');
      expect(result).not.toContain('Awesome T-Shirt');
      expect(result).toContain('## Collections');
    });

    it('should skip collections section when disabled', () => {
      const configNoCollections: LlmsTxtConfig = {
        ...mockConfig,
        includeCollections: false,
      };

      const options: GenerateLlmsTxtOptions = {
        store: mockStore,
        config: configNoCollections,
        products: mockProducts,
        collections: mockCollections,
      };

      const result = generateLlmsTxt(options);

      expect(result).toContain('## Products');
      expect(result).not.toContain('## Collections');
      expect(result).not.toContain('Summer Collection');
    });

    it('should include custom instructions when provided', () => {
      const configWithInstructions: LlmsTxtConfig = {
        ...mockConfig,
        customInstructions: 'We offer free shipping on orders over $50.',
      };

      const options: GenerateLlmsTxtOptions = {
        store: mockStore,
        config: configWithInstructions,
        products: mockProducts,
        collections: mockCollections,
      };

      const result = generateLlmsTxt(options);

      expect(result).toContain('## Additional Information');
      expect(result).toContain('We offer free shipping on orders over $50.');
    });

    it('should extract main categories from products', () => {
      const options: GenerateLlmsTxtOptions = {
        store: mockStore,
        config: mockConfig,
        products: mockProducts,
        collections: mockCollections,
      };

      const result = generateLlmsTxt(options);

      // Should mention product types in summary
      expect(result).toContain('Apparel');
      expect(result).toContain('Footwear');
    });

    it('should handle empty products array', () => {
      const options: GenerateLlmsTxtOptions = {
        store: mockStore,
        config: mockConfig,
        products: [],
        collections: mockCollections,
      };

      const result = generateLlmsTxt(options);

      // Should still generate valid file
      expect(result).toContain('# Test Store');
      expect(result).toContain('## Collections');
      // Products section should not appear with empty products
      expect(result).not.toMatch(/## Products\n\n## /);
    });

    it('should handle empty collections array', () => {
      const options: GenerateLlmsTxtOptions = {
        store: mockStore,
        config: mockConfig,
        products: mockProducts,
        collections: [],
      };

      const result = generateLlmsTxt(options);

      expect(result).toContain('# Test Store');
      expect(result).toContain('## Products');
      // Collections section header should not appear without content
    });

    it('should truncate long descriptions', () => {
      const longDescription = 'A'.repeat(300);
      const productsWithLongDesc: LlmsTxtProduct[] = [
        {
          ...mockProducts[0],
          description: longDescription,
        },
      ];

      const options: GenerateLlmsTxtOptions = {
        store: mockStore,
        config: mockConfig,
        products: productsWithLongDesc,
        collections: [],
      };

      const result = generateLlmsTxt(options);

      // Description should be truncated to ~150 chars
      expect(result).toContain('...');
      // Result should be much shorter than having full 300 char description
      expect(result.length).toBeLessThan(longDescription.length + 600);
    });

    it('should generate correct URLs', () => {
      const options: GenerateLlmsTxtOptions = {
        store: mockStore,
        config: mockConfig,
        products: mockProducts,
        collections: mockCollections,
      };

      const result = generateLlmsTxt(options);

      // Check product URLs
      expect(result).toContain('https://test-store.myshopify.com/products/awesome-t-shirt');
      expect(result).toContain('https://test-store.myshopify.com/products/cool-sneakers');

      // Check collection URLs
      expect(result).toContain('https://test-store.myshopify.com/collections/summer-collection');
      expect(result).toContain('https://test-store.myshopify.com/collections/new-arrivals');
    });
  });
});
