import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'GDPR Compliance - Surfaced',
  description: 'GDPR compliance information for Surfaced AI Visibility Optimization App',
  robots: 'index, follow',
};

export default function GDPRPage() {
  return (
    <div style={{
      maxWidth: '800px',
      margin: '0 auto',
      padding: '40px 20px',
      fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      lineHeight: '1.6',
      color: '#333'
    }}>
      <h1 style={{ borderBottom: '2px solid #0EA5E9', paddingBottom: '10px' }}>
        GDPR Compliance
      </h1>
      <p style={{ color: '#666', marginBottom: '30px' }}>
        Last updated: January 23, 2025
      </p>

      <section style={{ marginBottom: '30px' }}>
        <h2>1. Our Commitment to GDPR</h2>
        <p>
          Surfaced is committed to protecting the privacy and personal data of all users
          in compliance with the General Data Protection Regulation (GDPR) and other
          applicable privacy laws including CCPA, CPRA, and UK GDPR.
        </p>
        <p>
          As a data processor acting on behalf of Shopify merchants (data controllers),
          we implement appropriate technical and organizational measures to ensure data
          protection by design and by default.
        </p>
      </section>

      <section style={{ marginBottom: '30px' }}>
        <h2>2. Data We Process</h2>

        <h3>2.1 Merchant Data</h3>
        <p>We process the following merchant data:</p>
        <ul>
          <li>Shop domain and store name</li>
          <li>Contact email (for account purposes)</li>
          <li>Encrypted access tokens (for API authentication)</li>
          <li>Subscription and billing information (via Shopify)</li>
        </ul>

        <h3>2.2 Product Data</h3>
        <p>We access and process:</p>
        <ul>
          <li>Product titles, descriptions, and handles</li>
          <li>Product images and ALT text</li>
          <li>Product metafields and tags</li>
          <li>AI readiness scores (generated by our analysis)</li>
        </ul>

        <h3>2.3 What We Do NOT Process</h3>
        <p style={{ fontWeight: 'bold', color: '#059669' }}>
          Surfaced does NOT collect, store, or process:
        </p>
        <ul>
          <li>Customer personal information (names, emails, addresses)</li>
          <li>Order or transaction data</li>
          <li>Payment information</li>
          <li>Customer browsing behavior</li>
          <li>Any data from store visitors</li>
        </ul>
      </section>

      <section style={{ marginBottom: '30px' }}>
        <h2>3. Legal Basis for Processing</h2>
        <p>We process data based on the following legal grounds:</p>
        <ul>
          <li>
            <strong>Contract Performance:</strong> Processing necessary to provide our
            services as described in our Terms of Service
          </li>
          <li>
            <strong>Legitimate Interest:</strong> To improve our services and ensure
            security
          </li>
          <li>
            <strong>Consent:</strong> When merchants install our app and agree to our
            terms
          </li>
        </ul>
      </section>

      <section style={{ marginBottom: '30px' }}>
        <h2>4. Your Rights Under GDPR</h2>
        <p>
          If you are located in the European Economic Area (EEA), United Kingdom, or
          another jurisdiction with similar privacy laws, you have the following rights:
        </p>

        <div style={{ background: '#f0f9ff', padding: '20px', borderRadius: '8px', marginTop: '15px' }}>
          <ul style={{ margin: 0 }}>
            <li style={{ marginBottom: '10px' }}>
              <strong>Right to Access:</strong> Request a copy of the personal data we hold about you
            </li>
            <li style={{ marginBottom: '10px' }}>
              <strong>Right to Rectification:</strong> Request correction of inaccurate or incomplete data
            </li>
            <li style={{ marginBottom: '10px' }}>
              <strong>Right to Erasure:</strong> Request deletion of your personal data (&quot;right to be forgotten&quot;)
            </li>
            <li style={{ marginBottom: '10px' }}>
              <strong>Right to Restrict Processing:</strong> Request limitation of data processing
            </li>
            <li style={{ marginBottom: '10px' }}>
              <strong>Right to Data Portability:</strong> Receive your data in a structured, machine-readable format
            </li>
            <li style={{ marginBottom: '10px' }}>
              <strong>Right to Object:</strong> Object to processing based on legitimate interests
            </li>
            <li>
              <strong>Right to Withdraw Consent:</strong> Withdraw consent at any time where processing is based on consent
            </li>
          </ul>
        </div>

        <p style={{ marginTop: '15px' }}>
          To exercise any of these rights, please contact us at{' '}
          <a href="mailto:support@surfaced.app" style={{ color: '#0EA5E9' }}>support@surfaced.app</a>.
          We will respond to your request within 30 days.
        </p>
      </section>

      <section style={{ marginBottom: '30px' }}>
        <h2>5. Shopify Compliance Webhooks</h2>
        <p>
          We comply with Shopify&apos;s mandatory data protection requirements by responding
          to the following webhook events:
        </p>

        <div style={{ background: '#fef3c7', padding: '20px', borderRadius: '8px', marginTop: '15px' }}>
          <h4 style={{ marginTop: 0 }}>customers/data_request</h4>
          <p style={{ margin: '5px 0' }}>
            When a customer requests their data, we respond confirming that we do not
            store any customer personal data.
          </p>

          <h4 style={{ marginTop: '15px' }}>customers/redact</h4>
          <p style={{ margin: '5px 0' }}>
            When requested to delete customer data, we confirm compliance (we do not
            store customer data).
          </p>

          <h4 style={{ marginTop: '15px' }}>shop/redact</h4>
          <p style={{ margin: '5px 0' }}>
            Within 48 hours of app uninstallation, we permanently delete all shop data
            including products audit data, visibility checks, settings, and access tokens.
          </p>
        </div>
      </section>

      <section style={{ marginBottom: '30px' }}>
        <h2>6. Data Security Measures</h2>
        <p>We implement robust security measures to protect your data:</p>
        <ul>
          <li>
            <strong>Encryption at Rest:</strong> Access tokens encrypted with AES-256-GCM
          </li>
          <li>
            <strong>Encryption in Transit:</strong> All data transmitted via HTTPS/TLS
          </li>
          <li>
            <strong>Secure Infrastructure:</strong> Hosted on Vercel with SOC 2 compliance
          </li>
          <li>
            <strong>Database Security:</strong> Vercel Postgres with encrypted connections
          </li>
          <li>
            <strong>Access Controls:</strong> Strict authentication using Shopify OAuth
          </li>
          <li>
            <strong>Monitoring:</strong> Real-time security monitoring and logging
          </li>
        </ul>
      </section>

      <section style={{ marginBottom: '30px' }}>
        <h2>7. Data Retention</h2>
        <p>
          We retain your data only for as long as necessary to provide our services:
        </p>
        <ul>
          <li>
            <strong>Active Subscription:</strong> Data retained while the app is installed
          </li>
          <li>
            <strong>After Uninstallation:</strong> All data permanently deleted within 24 hours
          </li>
          <li>
            <strong>Backups:</strong> Automatically purged within 30 days
          </li>
        </ul>
        <p>
          You can request immediate deletion of your data at any time by contacting us.
        </p>
      </section>

      <section style={{ marginBottom: '30px' }}>
        <h2>8. International Data Transfers</h2>
        <p>
          Our services are hosted in regions that may include the United States and Europe.
          When data is transferred outside the EEA, we ensure appropriate safeguards are in
          place, including:
        </p>
        <ul>
          <li>Standard Contractual Clauses (SCCs) approved by the European Commission</li>
          <li>Data processing agreements with all sub-processors</li>
          <li>Adequacy decisions where applicable</li>
        </ul>
      </section>

      <section style={{ marginBottom: '30px' }}>
        <h2>9. Sub-Processors</h2>
        <p>We use the following sub-processors to deliver our services:</p>
        <table style={{ width: '100%', borderCollapse: 'collapse', marginTop: '15px' }}>
          <thead>
            <tr style={{ background: '#f1f5f9' }}>
              <th style={{ padding: '12px', textAlign: 'left', border: '1px solid #e2e8f0' }}>Provider</th>
              <th style={{ padding: '12px', textAlign: 'left', border: '1px solid #e2e8f0' }}>Purpose</th>
              <th style={{ padding: '12px', textAlign: 'left', border: '1px solid #e2e8f0' }}>Location</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td style={{ padding: '12px', border: '1px solid #e2e8f0' }}>Vercel</td>
              <td style={{ padding: '12px', border: '1px solid #e2e8f0' }}>Hosting &amp; Infrastructure</td>
              <td style={{ padding: '12px', border: '1px solid #e2e8f0' }}>US/EU</td>
            </tr>
            <tr>
              <td style={{ padding: '12px', border: '1px solid #e2e8f0' }}>Shopify</td>
              <td style={{ padding: '12px', border: '1px solid #e2e8f0' }}>Authentication &amp; Billing</td>
              <td style={{ padding: '12px', border: '1px solid #e2e8f0' }}>US/CA</td>
            </tr>
            <tr>
              <td style={{ padding: '12px', border: '1px solid #e2e8f0' }}>OpenRouter</td>
              <td style={{ padding: '12px', border: '1px solid #e2e8f0' }}>AI API Gateway</td>
              <td style={{ padding: '12px', border: '1px solid #e2e8f0' }}>US</td>
            </tr>
          </tbody>
        </table>
      </section>

      <section style={{ marginBottom: '30px' }}>
        <h2>10. Data Breach Notification</h2>
        <p>
          In the event of a personal data breach that is likely to result in a risk to your
          rights and freedoms, we will:
        </p>
        <ul>
          <li>Notify the relevant supervisory authority within 72 hours</li>
          <li>Notify affected merchants without undue delay</li>
          <li>Document the breach and remediation steps taken</li>
        </ul>
      </section>

      <section style={{ marginBottom: '30px' }}>
        <h2>11. Data Protection Officer</h2>
        <p>
          For any questions regarding our data protection practices or to exercise your
          rights, please contact:
        </p>
        <ul>
          <li><strong>Email:</strong> <a href="mailto:support@surfaced.app" style={{ color: '#0EA5E9' }}>support@surfaced.app</a></li>
        </ul>
      </section>

      <section style={{ marginBottom: '30px' }}>
        <h2>12. Complaints</h2>
        <p>
          If you believe we have not handled your data correctly, you have the right to
          lodge a complaint with your local data protection authority. For EEA residents,
          you can find your local authority at{' '}
          <a
            href="https://edpb.europa.eu/about-edpb/about-edpb/members_en"
            target="_blank"
            rel="noopener noreferrer"
            style={{ color: '#0EA5E9' }}
          >
            https://edpb.europa.eu
          </a>.
        </p>
      </section>

      <section style={{
        marginTop: '40px',
        paddingTop: '20px',
        borderTop: '1px solid #eee',
        color: '#666',
        fontSize: '14px'
      }}>
        <p>
          This page is provided in compliance with GDPR Article 13 and 14 requirements
          for transparency. For our full privacy practices, please see our{' '}
          <a href="/privacy" style={{ color: '#0EA5E9' }}>Privacy Policy</a>.
        </p>
        <p style={{ marginTop: '10px' }}>
          This application is built in compliance with the{' '}
          <a
            href="https://www.shopify.com/partners/terms"
            target="_blank"
            rel="noopener noreferrer"
            style={{ color: '#0EA5E9' }}
          >
            Shopify Partner Program Agreement
          </a>{' '}
          and follows Shopify&apos;s data protection requirements.
        </p>
      </section>
    </div>
  );
}
